### ISSUE TITLE
Installation error on CentOS. "wrong libfann version" where installed version is 2.2

### ISSUE THREAD

**Issue by mwng81** [bukka/php-fann#17]
Hi
I'm submitting this as it may be a different issue. I'm having troubles installing php-fann on CentOS. I'm getting 

"configure: error: wrong libfann version (you need at least version 2.1) or lib not found"

even though

"checking for libfann headers in default path... found in /usr/local" and installed version is 2.2

Thanks a lot for the help.

**Comment by mwng81** [comment]
Make sure you remove the libfann libraries and do a clean reinstall of the latest version!

**Comment by bukka** [comment]
:)

**Comment by mwng81** [comment]
I think it should be specified on the PHP page that we need to completely remove all old libfann libs and install 2.2 before running the install of php-fann. Otherwise it's confusing to users with limited knowledge of command line unix.
Thanks for the lib, it now works like a charm!

**Comment by bukka** [comment]
I will add a note about that. I also have to fix few small doc issue so I will re-open this and close when I get time to do that.

**Comment by mwng81** [comment]
Thanks a lot !

**Comment by bukka** [comment]
Should be fixed and soon live - all committed

**Comment by rmc135** [comment]
I had the same issue under FreeBSD 12.3, where the FANN headers were found, but configure complained the library itself was not found/wrong version.

The error message is a little ambiguous, and really seems to mean "the test compile failed for an unknown reason"

After fooling around with compiling manually from github source, I figured out that on my system the library path was not included by default. The fix is simple: set LDFLAGS=-L to force a path.

LDFLAGS="-L/usr/local/lib" pecl install fann-1.2.0RC2

(this will also work with configure if compiling manually)

Apologies for the necro-bump, but hopefully this may assist someone else with the same problem in the future.
