### ISSUE TITLE
Thansk but some example require

### ISSUE THREAD

**Issue by mhf-ir** [bukka/php-fann#8]
First thanks for bring FANN to php. also we need more documentation in PHP based application.

**Comment by geekgirljoy** [comment]
Hello Bukka, I am doing a series of blog posts on how to use FANN along with PHP and during my initial testing and experimentation I created the additional logic gates to go along with the XOR example (AND, OR, NOT, NAND, NOR, XNOR) and because you said you planned on adding more examples, I was wondering if you would be interested in including them in the repo?

**Comment by bukka** [comment]
Sorry for the late reply @geekgirljoy . That would be awesome. If you could send a PR to add something to examples dir, that would be great! Thanks.

**Comment by geekgirljoy** [comment]
Will do! I will give the code a quick review before doing a pull request. Thank you for your time and considering.

**Comment by bukka** [comment]
IIRC extended examples were added so closing this.
